language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t fphuang/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fphuang/docker-react npm run test